// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ccfProbeCcfEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Ppid        uint32
	Comm        [16]int8
	EventType   uint32
	Uid         uint32
	Gid         uint32
	Path        [256]int8
	DstPath     [256]int8
	_           [4]byte
}

// loadCcfProbe returns the embedded CollectionSpec for ccfProbe.
func loadCcfProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CcfProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ccfProbe: %w", err)
	}

	return spec, err
}

// loadCcfProbeObjects loads ccfProbe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ccfProbeObjects
//	*ccfProbePrograms
//	*ccfProbeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCcfProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCcfProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ccfProbeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ccfProbeSpecs struct {
	ccfProbeProgramSpecs
	ccfProbeMapSpecs
	ccfProbeVariableSpecs
}

// ccfProbeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ccfProbeProgramSpecs struct {
	TpExec   *ebpf.ProgramSpec `ebpf:"tp_exec"`
	TpOpenat *ebpf.ProgramSpec `ebpf:"tp_openat"`
	TpRename *ebpf.ProgramSpec `ebpf:"tp_rename"`
	TpSetuid *ebpf.ProgramSpec `ebpf:"tp_setuid"`
	TpUnlink *ebpf.ProgramSpec `ebpf:"tp_unlink"`
	TpWrite  *ebpf.ProgramSpec `ebpf:"tp_write"`
}

// ccfProbeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ccfProbeMapSpecs struct {
	CcfEvents  *ebpf.MapSpec `ebpf:"ccf_events"`
	CcfScratch *ebpf.MapSpec `ebpf:"ccf_scratch"`
	PidFilter  *ebpf.MapSpec `ebpf:"pid_filter"`
}

// ccfProbeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ccfProbeVariableSpecs struct {
}

// ccfProbeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCcfProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ccfProbeObjects struct {
	ccfProbePrograms
	ccfProbeMaps
	ccfProbeVariables
}

func (o *ccfProbeObjects) Close() error {
	return _CcfProbeClose(
		&o.ccfProbePrograms,
		&o.ccfProbeMaps,
	)
}

// ccfProbeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCcfProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ccfProbeMaps struct {
	CcfEvents  *ebpf.Map `ebpf:"ccf_events"`
	CcfScratch *ebpf.Map `ebpf:"ccf_scratch"`
	PidFilter  *ebpf.Map `ebpf:"pid_filter"`
}

func (m *ccfProbeMaps) Close() error {
	return _CcfProbeClose(
		m.CcfEvents,
		m.CcfScratch,
		m.PidFilter,
	)
}

// ccfProbeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCcfProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ccfProbeVariables struct {
}

// ccfProbePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCcfProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ccfProbePrograms struct {
	TpExec   *ebpf.Program `ebpf:"tp_exec"`
	TpOpenat *ebpf.Program `ebpf:"tp_openat"`
	TpRename *ebpf.Program `ebpf:"tp_rename"`
	TpSetuid *ebpf.Program `ebpf:"tp_setuid"`
	TpUnlink *ebpf.Program `ebpf:"tp_unlink"`
	TpWrite  *ebpf.Program `ebpf:"tp_write"`
}

func (p *ccfProbePrograms) Close() error {
	return _CcfProbeClose(
		p.TpExec,
		p.TpOpenat,
		p.TpRename,
		p.TpSetuid,
		p.TpUnlink,
		p.TpWrite,
	)
}

func _CcfProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ccfprobe_bpfeb.o
var _CcfProbeBytes []byte
