// Package collector loads the eBPF probe and streams RawEvents to the pipeline.
//
// Responsibilities:
//   - Compile + load the eBPF object (via cilium/ebpf)
//   - Attach tracepoints
//   - Read from the perf event ring buffer
//   - Deserialize kernel structs → event.RawEvent
//   - Block-list the agent's own PID in the kernel filter map
package collector

import (
	"context"
	"encoding/binary"
	"fmt"
	"os"
	"time"
	"unsafe"

	"github.com/ccf-agent/pkg/event"
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"go.uber.org/zap"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc ${BPF_CLANG} -cflags "-O2 -g -Wall -I../../ebpf -I${LIBBPF_INCLUDE} -I${KERNEL_HEADERS}/include" ccfProbe ../../ebpf/ccf_probe.c

// kernelEvent must match the C struct ccf_event byte-for-byte.
// Any change to the C struct requires a matching change here.
type kernelEvent struct {
	TimestampNS uint64
	PID         uint32
	PPID        uint32
	Comm        [16]byte
	EventType   uint32
	UID         uint32
	GID         uint32
	Path        [256]byte
	DstPath     [256]byte
}

// kernelEventType mirrors the #define values in ccf_probe.c
type kernelEventType uint32

const (
	evtFileOpen   kernelEventType = 0
	evtFileWrite  kernelEventType = 1
	evtFileRename kernelEventType = 2
	evtFileDelete kernelEventType = 3
	evtExec       kernelEventType = 4
	evtSetUID     kernelEventType = 5
)

// Config holds tunable parameters for the collector.
type Config struct {
	// PerfBufferPageCount is the number of memory-mapped pages per CPU for
	// the perf ring buffer. Must be a power of 2. Higher = fewer drops under
	// burst load at the cost of more memory.
	PerfBufferPageCount int

	// PIDBlocklist contains PIDs that will be silently dropped by the kernel
	// filter map (agent itself, systemd, kthreadd, etc.).
	PIDBlocklist []uint32

	// DroppedEventLogInterval controls how often drop counters are logged.
	DroppedEventLogInterval time.Duration
}

func DefaultConfig() Config {
	return Config{
		PerfBufferPageCount:     64,
		PIDBlocklist:            []uint32{uint32(os.Getpid())},
		DroppedEventLogInterval: 10 * time.Second,
	}
}

// Collector owns the eBPF objects and exposes a streaming channel of RawEvents.
type Collector struct {
	cfg    Config
	log    *zap.Logger
	objs   ccfProbeObjects // generated by bpf2go
	links  []link.Link
	reader *perf.Reader
}

// New loads the compiled eBPF object into the kernel and attaches tracepoints.
// Caller must call Close() when done.
func New(cfg Config, log *zap.Logger) (*Collector, error) {
	c := &Collector{cfg: cfg, log: log}

	// Load pre-compiled eBPF objects (generated by go:generate).
	if err := loadCcfProbeObjects(&c.objs, nil); err != nil {
		return nil, fmt.Errorf("load ebpf objects: %w", err)
	}

	if err := c.attachTracepoints(); err != nil {
		c.objs.Close()
		return nil, fmt.Errorf("attach tracepoints: %w", err)
	}

	if err := c.populatePIDFilter(); err != nil {
		c.closeLinks()
		c.objs.Close()
		return nil, fmt.Errorf("populate pid filter: %w", err)
	}

	rd, err := perf.NewReader(c.objs.CcfEvents, cfg.PerfBufferPageCount*os.Getpagesize())
	if err != nil {
		c.closeLinks()
		c.objs.Close()
		return nil, fmt.Errorf("create perf reader: %w", err)
	}
	c.reader = rd

	log.Info("collector started",
		zap.Int("perf_pages_per_cpu", cfg.PerfBufferPageCount),
		zap.Int("pid_blocklist_size", len(cfg.PIDBlocklist)),
	)
	return c, nil
}

// Run streams RawEvents into out until ctx is cancelled or a fatal error occurs.
// Designed to be run in its own goroutine.
func (c *Collector) Run(ctx context.Context, out chan<- event.RawEvent) error {
	dropTicker := time.NewTicker(c.cfg.DroppedEventLogInterval)
	defer dropTicker.Stop()

	var totalDropped uint64

	for {
		select {
		case <-ctx.Done():
			return nil
		case <-dropTicker.C:
			if totalDropped > 0 {
				c.log.Warn("perf ring buffer drops", zap.Uint64("count", totalDropped))
				totalDropped = 0
			}
		default:
		}

		record, err := c.reader.Read()
		if err != nil {
			if perf.IsUnknownEvent(err) {
				continue
			}
			return fmt.Errorf("perf reader: %w", err)
		}

		totalDropped += uint64(record.LostSamples)

		raw, err := c.deserialize(record.RawSample)
		if err != nil {
			c.log.Debug("deserialize error", zap.Error(err))
			continue
		}

		select {
		case out <- raw:
		case <-ctx.Done():
			return nil
		default:
			// Channel full — drop and count; prevents collector blocking pipeline.
			totalDropped++
		}
	}
}

// Close detaches tracepoints and unloads eBPF objects.
func (c *Collector) Close() {
	if c.reader != nil {
		c.reader.Close()
	}
	c.closeLinks()
	c.objs.Close()
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

func (c *Collector) attachTracepoints() error {
	type tp struct {
		group   string
		name    string
		program *ebpf.Program
	}

	// TODO: update program field names after go:generate runs — these match
	// the SEC() names in ccf_probe.c converted to Go identifiers by bpf2go.
	probes := []tp{
		{"syscalls", "sys_enter_openat",   c.objs.TpOpenat},
		{"syscalls", "sys_enter_write",    c.objs.TpWrite},
		{"syscalls", "sys_enter_renameat2",c.objs.TpRename},
		{"syscalls", "sys_enter_unlinkat", c.objs.TpUnlink},
		{"sched",    "sched_process_exec", c.objs.TpExec},
		{"syscalls", "sys_enter_setuid",   c.objs.TpSetuid},
	}

	for _, p := range probes {
		l, err := link.Tracepoint(p.group, p.name, p.program, nil)
		if err != nil {
			return fmt.Errorf("attach %s/%s: %w", p.group, p.name, err)
		}
		c.links = append(c.links, l)
	}
	return nil
}

func (c *Collector) populatePIDFilter() error {
	val := uint8(1)
	for _, pid := range c.cfg.PIDBlocklist {
		if err := c.objs.PidFilter.Put(pid, val); err != nil {
			return fmt.Errorf("pid %d: %w", pid, err)
		}
	}
	return nil
}

func (c *Collector) closeLinks() {
	for _, l := range c.links {
		l.Close()
	}
	c.links = nil
}

func (c *Collector) deserialize(raw []byte) (event.RawEvent, error) {
	if len(raw) < int(unsafe.Sizeof(kernelEvent{})) {
		return event.RawEvent{}, fmt.Errorf("short record: %d bytes", len(raw))
	}

	var ke kernelEvent
	// Use little-endian (x86 / arm64 are both LE).
	ke.TimestampNS = binary.LittleEndian.Uint64(raw[0:8])
	ke.PID         = binary.LittleEndian.Uint32(raw[8:12])
	ke.PPID        = binary.LittleEndian.Uint32(raw[12:16])
	copy(ke.Comm[:], raw[16:32])
	ke.EventType   = binary.LittleEndian.Uint32(raw[32:36])
	ke.UID         = binary.LittleEndian.Uint32(raw[36:40])
	ke.GID         = binary.LittleEndian.Uint32(raw[40:44])
	copy(ke.Path[:], raw[44:300])
	copy(ke.DstPath[:], raw[300:556])

	evt := event.RawEvent{
		TimestampNS: ke.TimestampNS,
		PID:         ke.PID,
		PPID:        ke.PPID,
		ProcessName: nullTermString(ke.Comm[:]),
		UID:         ke.UID,
		GID:         ke.GID,
		Path:        nullTermString(ke.Path[:]),
		DstPath:     nullTermString(ke.DstPath[:]),
	}

	switch kernelEventType(ke.EventType) {
	case evtFileOpen:
		evt.Type = event.FileOpen
	case evtFileWrite:
		evt.Type = event.FileWrite
	case evtFileRename:
		evt.Type = event.FileRename
	case evtFileDelete:
		evt.Type = event.FileDelete
	case evtExec:
		evt.Type = event.Exec
	case evtSetUID:
		evt.Type = event.SetUID
	default:
		return event.RawEvent{}, fmt.Errorf("unknown event type: %d", ke.EventType)
	}

	return evt, nil
}

// nullTermString converts a null-terminated byte slice to a Go string.
func nullTermString(b []byte) string {
	for i, v := range b {
		if v == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}
